### ISSUE TITLE
Updating first short table for measurementProtocol

### ISSUE THREAD

**Issue by wavingtowaves** [ess-dive-community/essdive-leaf-gas-exchange#2]
## Change documentation

* Documentation reference (URL): https://github.com/ess-dive-community/essdive-leaf-gas-exchange/blob/master/dataTypesProtocols.md
* Submitter: Rob Crystal-Ornelas
* Justification (why is this change necessary?): When I parsed the CSV into markdown, I wasn't sure how to fill in the measurementProtocols table

I suggest the following changes: Updating where I left NA in the first short table so that it accurately reflects that the protocol is required for all datatypes. Also, mostly just testing out GitHub issues for this repo

**Comment by regnans** [comment]
Fixed the NA issue. Added the reference list (not perfectly formatted yet), but there. 
Testing, 1, 2!
