### ISSUE TITLE
Modifying contribute.MD templates

### ISSUE THREAD

**Issue by wavingtowaves** [ess-dive-community/essdive-leaf-gas-exchange#3]
## Change documentation

* Documentation reference (URL): https://github.com/ess-dive-community/essdive-leaf-gas-exchange/blob/master/contribute.md
* Submitter: Rob Crystal-Ornelas
* Justification (why is this change necessary?): Make submitting issues more efficient since we can avoid copy and pasting templates

I suggest the following changes: I propose changing the way we display the issue templates from how we have them in the contribute.md document which requires copy and pasting to a new format that avoids copy and pasting templates.  See an example [here](https://github.com/ess-dive-community/essdive-sample-id-metadata/issues). When you click `new issue` you can then select from 3 different types of issues, and the templates from your contributing file will autogenerate.  Let me know if you like this format and I can make the change.

**Comment by regnans** [comment]
I like the new suggested format very much. So clean. Perhaps keep the three categories of issues already defined, and, only if it's easy, add a "Other comment or feedback" option?

**Comment by regnans** [comment]
Now I see that at the bottom there is a "open a blank issue" option, but, I still think having "Other" in the list would be good. The option as the bottom for blank issue is not obvious if you are not familiar with the layout of the page.

**Comment by wavingtowaves** [comment]
I just added three issue templates and included a fourth template that gives visitors another option to submit more general suggestions.

**Comment by wavingtowaves** [comment]
Also, @regnans in re-writing some of the wording for the "How to contribute" part of the readme file, I suggest also adding in this text (from Joan's repo) citing Darwin Core who provided some of the text for our issue templates: 

The issue templates we use are modeled from that provided by Darwin Core:
Darwin Core maintenance group, Biodiversity Information Standards (TDWG) (2014). Darwin Core. Zenodo. https://doi.org/10.5281/zenodo.592792

**Comment by regnans** [comment]
Looks good. I have added text and a link to the readme.

**Comment by regnans** [comment]
I'm happy to now delete contribute.md

**Comment by regnans** [comment]
Contribute gone, and Summary.md updated.
