### ISSUE TITLE
GitBook doesn't link to most recent version of methodsMetadataTemplate

### ISSUE THREAD

**Issue by wavingtowaves** [ess-dive-community/essdive-leaf-gas-exchange#5]
* Submitter: Rob C-O

Hi @regnans just keeping track of this gitbook issue we are having here.

To summarize: 

When downloading the templates directly from GitHub we get:  
-  instrumentDetailsTemplate v1.0 
- methodsMetadataTemplate v1.0.2

When I click the two template links from this page on GitBook: https://ess-dive.gitbook.io/leaf-level-gas-exchange/#getting-started 

I can download both of what appear to be the same Excel files.  

- methodsMetadataTemplate v1.0.2 (updated 16 days ago)
- instrumentDetailsTemplate v1.0 (updated december 2020)

However, on the instructions page, we get linked to an older version of the methodsMetadataTemplate:
- methodsMetadataTemplate v1.0 (updated December 2020) 
- instrumentDetailsTemplate  v1.0 (updated december 2020)

I have a support ticket into GitBook, so I'll update with the solution when I hear back

**Comment by wavingtowaves** [comment]
Response from GitBook support:

> I am afraid this is a limitation with our git sync feature currently.
> One way to overcome this is use an absolute link to the asset:
> https://github.com/ess-dive-community/essdive-leaf-gas-exchange/master/templates/methodsMetadataTemplate.xlsx
> That's not ideal if you need to use branches in your GitHub repository, or you ever want to rename the master branch. It should work however.

So I'll plan to update the links within our GitHub repo, and double check that they are linking to the most up-to-date version of the excel files.

**Comment by wavingtowaves** [comment]
Links to templates in both the README and Instructions.md documents are now updated and use the absolute link that GitBook support recommends.

@regnans I think the issue is read to close once you double check and make sure everything is 👍🏻

**Comment by regnans** [comment]
Looks good! thanks for sorting this out. Will close now.
